from .crawl_routes import router as crawl_router
from .scrapping_routes import router as scrapping_router
from .song_routes import router as song_router
from .db_routes import router as db_router
from .health_routes import router as health_router
from .artist_routes import router as artist_router
from .spotify_routes import router as spotify_router
from .playlist_routes import router as playlist_router
from .algorithms_routes import router as algorithms_router
from .mysql_routes import router as mysql_router
from .user_routes import router as user_router