services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bounsic-backend
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.dev
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "1801:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
