services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    init: true
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  db_data: