# Utiliza la imagen de Nginx
FROM nginx:latest

# Copia tu configuración personalizada de Nginx
COPY ./bounsic-back/nginx.conf /etc/nginx/nginx.conf

# Copia los certificados SSL (usa tus certificados existentes)
COPY ./bounsic-back/cert/cert.pem /etc/ssl/certs/cert.pem
COPY ./bounsic-back/cert/key.pem /etc/ssl/private/key.pem

# Exponer el puerto 443 para HTTPS
EXPOSE 443
