# Etapa de construcción para Python
FROM python:3.11.9-slim AS build

# Establecer directorio de trabajo
WORKDIR /app

# Copiar archivos de dependencias
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente del backend
COPY . .

# Etapa de producción con Nginx
FROM nginx:alpine

# Instalar Python y las dependencias necesarias
RUN apk add --no-cache python3 py3-pip

# Crear estructura de directorios
RUN mkdir -p /app /etc/nginx/sites-available

# Copiar desde la etapa de construcción
COPY --from=build /app /app
COPY --from=build /usr/local/lib/python3.11/site-packages /usr/lib/python3.11/site-packages

# Instalar uvicorn específicamente en esta etapa
RUN pip3 install --no-cache-dir uvicorn

# Copiar configuración de Nginx
COPY ./default /etc/nginx/sites-available/
COPY ./nginx.conf /etc/nginx/

# Puerto expuesto
EXPOSE 1801

# Script de inicio para ejecutar tanto nginx como la aplicación con Uvicorn
COPY ./start.sh /start.sh
RUN chmod +x /start.sh

CMD ["/start.sh"]