version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bounsic-backend
    expose:
      - "8000"
    networks:
      - bounsic-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: bounsic-nginx
    ports:
      - "443:443"
    depends_on:
      - backend
    networks:
      - bounsic-network
    volumes:
      - ./bounsic-back/cert/cert.pem:/etc/ssl/certs/cert.pem
      - ./bounsic-back/cert/key.pem:/etc/ssl/private/key.pem

networks:
  bounsic-network:
    driver: bridge
