# Utiliza la imagen de Nginx
FROM nginx:latest

# Copia tu configuración personalizada de Nginx
COPY ./bounsic-back/nginx.conf /etc/nginx/nginx.conf

# Copia el certificado SSL autofirmado
COPY ./bounsic-back/cert/selfsigned.crt /etc/ssl/certs/cert.pem
COPY ./bounsic-back/cert/selfsigned.key /etc/ssl/private/key.pem

# Exponer el puerto 443 para HTTPS
EXPOSE 443
