from .song_controller import get_song_by_artist_controller, get_song_by_title_controller, get_song_image_controller,get_songs_by_genre_controller, insert_bs_controller
from .bert_controller import bert_request
from .crawl_controller import crawl_request
from .db_controller import get_songs_request,create_one_song_request
from .scrapping_controller import get_youtube_scrapping_request,search_youtube_request,get_youtube_download_request, get_song_lyrics
from .algorithms_controller import fingerprint