name: Deploy to Azure

on:
  workflow_run:
    workflows: ["Dockerize Frontend"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bounsic-front'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_ca13cff80fdd45bb9ea199ced09f0e1b }}
          images: 'bounsic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_25ea92dee1494c22a18d8ea8268299e7 }}/bounsic-front:${{ github.sha }}'
