name: Dockerize and Deploy Streaming Service

on:
  push:
      branches:
        - feat/deploy-streaming
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  dockerize_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t bounsic-streaming:latest ./streaming

      - name: Verify Docker image
        run: |
          docker inspect bounsic-streaming:latest || exit 1
          docker run --rm bounsic-streaming:latest ls /app || exit 1
      - name: Compress and save image
        run: docker save bounsic-streaming:latest | gzip > bounsic-streaming.tar.gz

      - name: Transfer files to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          port: 22
          source: "bounsic-streaming.tar.gz"
          target: "/home/${{ secrets.AZURE_VM_USER }}/bounsic/"

      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd /home/${{ secrets.AZURE_VM_USER }}/bounsic
            # Cargar imagen
            docker load -i bounsic-streaming.tar.gz || exit 1
            # Detener y eliminar contenedor anterior si existe
            docker stop bounsic-streaming >/dev/null 2>&1 || true
            docker rm bounsic-streaming >/dev/null 2>&1 || true
            # Ejecutar nuevo contenedor con variables de entorno
            docker run -d \
            --name bounsic-streaming \
            -p 1801:8000 \
            --restart always \
            $(echo "${{ vars.ENV_BACK }}" | sed 's/\([^=]*\)=\(.*\)/-e \1=\2 /g') \
            bounsic-back:latest
            # Verificar despliegue
            sleep 5
            docker ps | grep bounsic-back || exit 1
