name: Dockerize Frontend

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  dockerize:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 🔹 Instalar Bun y agregarlo al PATH
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "BUN_INSTALL=$HOME/.bun" >> $GITHUB_ENV
          echo "PATH=$HOME/.bun/bin:$PATH" >> $GITHUB_ENV
          source $HOME/.bashrc
        shell: bash

      - name: Install dependencies and build frontend
        working-directory: ./bounsic-front
        run: |
          bun install
          bun run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: https://bounsic.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_25ea92dee1494c22a18d8ea8268299e7 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_92b12e7f7a664d05ab43b76d0015ba43 }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./bounsic-front/Dockerfile
          push: true
          tags: bounsic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_25ea92dee1494c22a18d8ea8268299e7 }}/bounsic-front:${{ github.sha }}
