name: Build and deploy container app to Azure Web App - streaming

on:
  push:
    branches:
      - feat/deploy-streaming
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bounsic.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ec3a57fb8d5348c8a57516d4dd9de55a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fe02c1d955574550877c3afa36464ecf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./streaming/Dockerfile
        push: true
        tags: bounsic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ec3a57fb8d5348c8a57516d4dd9de55a }}/streaming:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'streaming'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ecf955fef3fd41e9aae33bd54b8467a2 }}
        images: 'bounsic.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ec3a57fb8d5348c8a57516d4dd9de55a }}/streaming:${{ github.sha }}'